import React, {useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import * as Dialog from '@radix-ui/react-dialog';
import * as Select from '@radix-ui/react-select';
window.pageEscapes=0;window.clicks=0;
document.addEventListener('keydown',e=>{if(e.key==='Escape') window.pageEscapes++;if(e.key==='m') window.soundClicks=(window.soundClicks||0)+1;});
function App(){
 const [single,setSingle]=useState(''),[review,setReview]=useState(false);
 useEffect(()=>{const f=()=>{setSingle(location.hash.slice(1));setReview(location.pathname==='/review');};window.addEventListener('popstate',f);return()=>window.removeEventListener('popstate',f);},[]);
 const [group,setGroup]=useState(false),[camera,setCamera]=useState(false),[mode,setMode]=useState('smart');
 return <><aside><a href='/'>Home</a><a href='/review' onClick={e=>{e.preventDefault();history.pushState({idx:1},'','/review');setReview(true);}}>Review</a><div className='flex-col'><button>All cameras</button><button>Home group</button><button className="text-muted-foreground" onClick={()=>setGroup(true)}><svg width="20" height="20"><path d="M0 0L20 20"/></svg>Edit groups</button></div></aside><div id='pageRoot' className='absolute'>{review?<video style={{width:800,height:450}}/>:single?<div><div><button id='singleBack'>返回</button><button id='sound'><div onClick={()=>window.soundClicks=(window.soundClicks||0)+1}>聲音</div></button></div><div id='player-container'><div data-camera={single} style={{height:450}}>Single camera</div></div></div>:<><div className='cards'>{['bedroom','livingroom','front2','front'].map(name=><div key={name} data-camera={name} onClick={()=>{window.clicks++;window.lastCamera=name;if(window.testSingle){history.pushState({usr:{cameraGroup:'Home'},idx:1},'','#'+name);setSingle(name);}}}>{name}</div>)}</div><button id='bottom'>Bottom</button></>}</div>
 <Dialog.Root open={group} onOpenChange={setGroup}><Dialog.Portal><Dialog.Overlay className='shade'/><Dialog.Content className='dialog' aria-describedby={undefined}><Dialog.Title>Group edit</Dialog.Title><div className='scroll'><input id='name' defaultValue='Home'/>{Array.from({length:10},(_,i)=><div className='row' key={i}><span>Camera {i}</span><Dialog.Root open={camera===i} onOpenChange={o=>setCamera(o?i:false)}><Dialog.Trigger id={'gear'+i}>Settings</Dialog.Trigger><Dialog.Portal><Dialog.Overlay className='shade'/><Dialog.Content className='dialog inner' aria-describedby={undefined}><Dialog.Title>Camera {i}</Dialog.Title><Select.Root value={mode} onValueChange={setMode}><Select.Trigger id='stream'><Select.Value/></Select.Trigger><Select.Portal><Select.Content position='popper' className='select'><Select.Viewport>{['smart','continuous','no-streaming'].map(v=><Select.Item key={v} value={v}><Select.ItemText>{v}</Select.ItemText></Select.Item>)}</Select.Viewport></Select.Content></Select.Portal></Select.Root><button id='cameraCancel' onClick={()=>setCamera(false)}>Cancel</button><button id='cameraSave' onClick={()=>setCamera(false)}>Save</button></Dialog.Content></Dialog.Portal></Dialog.Root><button role='switch' aria-checked='true'>Enabled</button></div>)}</div><button id='groupCancel' onClick={()=>setGroup(false)}>Cancel</button><button id='groupSave' onClick={()=>setGroup(false)}>Save</button></Dialog.Content></Dialog.Portal></Dialog.Root></>;
}
createRoot(document.getElementById('root')).render(<App/>);
